name: Docker Image CI

on: [push]

env:
  IMAGE_NAME: andreasluedtke/alpine-psql

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag $IMAGE_NAME
        docker image ls

    - name: Log into registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push image
      run: |
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        echo "2 - "$VERSION

        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        echo "3 - "$VERSION

        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest
        echo "4 - "$VERSION

        echo "5 - "IMAGE_ID=$IMAGE_ID
        echo "6 - "VERSION=$VERSION

        # docker tag image $IMAGE_ID:$VERSION
        docker push $IMAGE_NAME:$VERSION
